### ISSUE TITLE
Set updates expectancy 

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd-community/helm-charts#27]
Given that these charts are community maintained, what's the expected time frame from the moment a Flux release is published to the moment `flux2` and `flux2-sync` charts are updated and released?

Should we add a notice to the main readme and to each chart readme that delays are expected and there are no guarantees about keeping up with upstream?

**Comment by dwerder** [comment]
Thats a good point and I would agree.
I would raise another question if we want to change the chart version number to actually match the flux version. So its easier for customers to see whats there.

For example:

Main Flux: 0.24.0
Community chart version : 0.24.0
Community chart patch: 0.24.0-1

**Comment by stefanprodan** [comment]
I can see how matching the flux version would make it easy for users to tell which Flux is available, but on the other hand how would you signal breaking changes to the chart?

**Comment by dmccaffery** [comment]
The chart manifest already has a field for appVersion for this purpose. This is where the version of flux should be defined, imho.

**Comment by dwerder** [comment]
@dmccaffery technically you are right. But its not so uncommon to set version and appVersion to be the same. Nevertheless it was just a suggestion.
Then we maybe need to add some annotation to the releases, to have an easy way (not viewing at the code) to see wich appVersion is in it.

**Comment by pierluigilenoci** [comment]
@dwerder I am totally against aligning the chart version with the software version for several reasons.

First of all, because they are different things and therefore they must have different versions.

Second and more important: between one version and the other of the software it is possible to have to release more than one version of the chart even if only to fix a bug of the chart.

In addition, changes in the chart can introduce breaking changes and semantic versioning serves to signal this too.

However, [appVersion](https://github.com/fluxcd-community/helm-charts/blob/main/charts/flux2/Chart.yaml#L8) explicitly says which version is used in the chart and is clearly indicated in the [Artifact Hub](https://artifacthub.io/packages/helm/fluxcd-community/flux2) as well. 

There are also other minor reasons (including some personal ones) but I would say that these are already enough to motivate my opposition.

**Comment by pierluigilenoci** [comment]
I agree with @stefanprodan to add a note that the chart is maintained on a voluntary basis and therefore there are no guarantees whatsoever.

**Comment by stefanprodan** [comment]
Given https://github.com/aws/containers-roadmap/issues/1593 I think it's imperative to set the right expectations for these charts in the main repo readme on on each chart readme.
